---
- name: 'Remove pm2 yarn'
  shell: sudo pm2 del yarn
  ignore_errors: True
  become: yes

- name: 'Cria pm2 yarn'
  shell: cd /var/www/site/ && sudo chmod -R 2775 . && sudo pm2 start yarn -- next start -p 80
  become: yes
